/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lwqnysvehxjubnzjsteq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3cW55c3ZlaHhqdWJuempzdGVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2NzE3MjMsImV4cCI6MjA4MjI0NzcyM30._wKtJChYXvMpt_-uZtpMN5Pheu-UltT7WgJdJHzzJ1M"